version: '3.8'

services:
  # NGINX (Frontend and Reverse Proxy)
  frontend:
    # Use the image we pushed to Docker Hub on my account
    image: gurshabo55/fastreact-frontend:latest
    restart: always
    ports:
      - "80:80"    # Expose HTTP to the world
      - "443:443"  # Ready for HTTPS in the future
    depends_on:
      - backend

  # FASTAPI (Backend Service)
  backend:
    image: gurshabo55/fastreact-backend:latest
    restart: always
    # No ports exposed to the host. Nginx proxies to it.
    volumes:
      # Mount the credentials file that the CI/CD script will create
      - ./google-credentials.json:/app/google-credentials.json:ro
    env_file:
      - ./.env.prod # Load production environment variables
    depends_on:
      - redis

  # REDIS (Message Broker)
  redis:
    image: "redis:7-alpine"
    restart: always

  # CELERY (Worker Service)
  worker:
    image: gurshabo55/fastreact-backend:latest # It uses the same image as the backend
    restart: always
    command: ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info"]
    volumes:
      - ./google-credentials.json:/app/google-credentials.json:ro
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - backend