# docker-compose.prod.yml

version: '3.8'

services:
  # --- NGINX (Frontend & Reverse Proxy) ---
  nginx:
    image: gurshabo55/fastreact-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  # --- FASTAPI (Backend Service) ---
  backend:
    image: gurshabo55/fastreact-backend:latest
    volumes:
      # Mount the credentials file into the container (read-only)
      - ./google-credentials.json:/app/google-credentials.json:ro
      # Mount a volume for the SQLite database to persist data
      - app_data:/app/data
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  # --- REDIS (Message Broker & Celery Backend) ---
  redis:
    image: "redis:7-alpine"

  # --- CELERY (Worker Service) ---
  worker:
    image: gurshabo55/fastreact-backend:latest
    command: ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info"]
    volumes:
      # Mount the credentials file into the container (read-only)
      - ./google-credentials.json:/app/google-credentials.json:ro
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - backend

volumes:
  app_data: # Define the named volume for persistence