services:
  # --- NGINX (Frontend Service) ---
  nginx:
    image: gurshabo55/fastreact-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  # --- FASTAPI (Backend Service) ---
  backend:
    image: gurshabo55/fastreact-backend:latest
    volumes:
      - ./google-credentials.json:/app/google-credentials.json:ro
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  # --- REDIS (Message Broker) ---
  redis:
    image: "redis:7-alpine"

  # --- CELERY (Worker Service) ---
  worker:
    image: gurshabo55/fastreact-backend:latest
    command: ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info"]
    volumes:
      - ./google-credentials.json:/app/google-credentials.json:ro
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - backend